### ISSUE TITLE
implement a carry functionality

### ISSUE THREAD

**Issue by X39** [X39/XMS2#32]
for an example about how to implement it, check the "drag" functionality

the involved files are more or less theese:
- https://github.com/X39/XMS2/blob/master/X39_MS2_Scripting/stringtable.xml
- https://github.com/X39/XMS2/blob/master/X39_MS2_Scripting/Functions/initModHelpers/addInteractionMenuEntries.sqf
- https://github.com/X39/XMS2/blob/master/X39_MS2_Scripting/Functions/initMod.sqf

please also try to prevent users from dragging when they carry something

**Comment by MrP0tter** [comment]
Taking a look into this one right now, for now I have just simply changed the animations because it looks like you just have the system executing the animation via the script, and then are using the stringtable(which I have got setup for carry as well). Looking for what needs work in the initMod.sqf. If you know for a fact that any of what I have won't work, let me know.

**Comment by MrP0tter** [comment]
Needs a fast re-adjustment of the position once the carried person is on the back of the carrier. I'll fix that as soon as a get a chance, unless you get to it first.
