### ISSUE TITLE
Temperature simulation is incorrect, Improovement is required in prone behaviour

### ISSUE THREAD

**Issue by Boozdeuvash** [X39/XMS2#39]
After getting shot by an AI with an AKM (Mod), i went to blackscreen unconscious and lost temperature to 0 in just a few seconds (less than 10). Then it said I dies to coldness. the end.

Note that I was running a few other mods including AGM (not AGM medical or any other medical systems). 

This did not happen when shot with another weapon (Stinger 9mm), but I didnt get shot enough to get into blackout.

will test with other vanilla/non-vaninnal weps.

**Comment by MrP0tter** [comment]
I'll run some tests as well on my end. Let us know if other weapons generate this problem, and do you know what mod the AKM  was from?

**Comment by X39** [comment]
Will check the temperature tick
Maybe there is something not implemented correctly

**Comment by X39** [comment]
An RPT log with the debug version would also help
Could you provideus one @boozdeuvash ?

**Comment by Boozdeuvash** [comment]
I'll try to reproduce on a clean instance so you can have a decent rpt instead of the disaster produced by ou current build. Shouldnt take too long.

**Comment by Boozdeuvash** [comment]
Another thing, disabling the temp feature in the init "solves" the problem. Not sure if it helps :)

**Comment by X39** [comment]
> disabling the temp feature 
as the problem relies on the temperature system it was to be expected that it wont happen when you disable the temperature system

from the RPT log perspective it looks like the calculation is not 100% correct
the important line about it is
> 12:36:39 "291.78 - X39_MS2_fnc_temperatureTick: _temperatureChange after prone reduction part of simulation: -0.2399"
meaning that the temperature is reduced after being prone (which is expected behaviour but !NOT THAT MUCH!)
gonna create new ticket to alter the temperature tick so that it works "propper" and like expected (its mostly just a change of the variables used ... so its just a default variable change)

thx for your help (ps. next time, report the entire RPT log at some file host, examples: http://dropbox.com http://mediafire.com http://mega.co.nz)

**Comment by X39** [comment]
Please check the prone tick, the current value is reducing the player temperature WAY to fast (see comments above for more information about that)

goal:
WAY smaller temperature loss by being prone (eg. 0.001 temperature loss for being prone)

**Comment by X39** [comment]
X39_MS2_var_Temperature_reductionByBeingPronePerTick default value is 0.25 which is WAY to much

will be reduced to 0.025 in next update
